name: build

on:
  push:

jobs:
  linux:
    strategy:
      matrix:
        target: [linux-arm64, linux-armhf, linux-i686, linux-riscv64, linux-x86_64]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: distrho/dpf-cmake-action@v1
        with:
          dpf_path: ./modules/dpf
          lto: true
          pawpaw: true
          target: ${{ matrix.target }}

  macos:
    env:
      WELCOME_TXT: ${{ github.workspace }}/utils/macos-installer-welcome.txt
    strategy:
      matrix:
        target: [macos-universal-10.15]
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: distrho/dpf-cmake-action@v1
        with:
          dpf_path: ./modules/dpf
          lto: true
          pawpaw: true
          target: ${{ matrix.target }}

  windows:
    strategy:
      matrix:
        target: [win32, win64]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: distrho/dpf-cmake-action@v1
        with:
          dpf_path: ./modules/dpf
          lto: true
          pawpaw: true
          target: ${{ matrix.target }}

  wasm:
    runs-on: ubuntu-22.04
    env:
      EMSCRIPTEN_VERSION: 3.1.27
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up cache
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            ~/emsdk
          key: emsdk
      - name: Set up dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -yqq brotli
          git clone https://github.com/emscripten-core/emsdk.git ~/emsdk
          cd ~/emsdk && ./emsdk install ${{ env.EMSCRIPTEN_VERSION }} && ./emsdk activate ${{ env.EMSCRIPTEN_VERSION }}

  pluginval:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: distrho/dpf-cmake-action@v1
        with:
          dpf_path: ./modules/dpf
          target: pluginval
